### ISSUE TITLE
🐈 Task: Ersilia tries to close docker containers when any model is fetched, even if from source

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1197]
### Summary

TODO

### Objective(s)

TODO

**Comment by DhanshreeA** [comment]
@Malikbadmus do you want to take a look into this?

**Comment by Malikbadmus** [comment]
@DhanshreeA, could you please provide more details about the task? I need a bit more information to understand it fully. Thank you.

**Comment by Malikbadmus** [comment]
@DhanshreeA , the conflicts happening at fetching are caused by [this method](https://github.com/ersilia-os/ersilia/blob/2a0ba90821f9226392df2bbc4dcfe1ab77306115/ersilia/serve/autoservice.py#L317). It is responsible for clearing temporary directories that match the prefix "ersilia-",  However, since we are running multiple sessions simultaneously, one session may delete a temporary directory that the other session is still using, in this case, **/tmp/ersilia-749mg2go/docker_pull.log**  for models running in a docker container.

The debug logger in the **clean_temp_dir** method only logs the directories it finds in the current session, so it doesn't detect or log directories created by other sessions. However, it still attempts to delete those directories if they match the "ersilia-" pattern, which is causing issues as other sessions are using them.

I was thinking of two ways this can be resolved, by using a model-specific or session-specific identifier to the temporary directories, though in a case where we are fetching the same model from different sources across multiple sessions, model-specific identifier will still run into same resource conflicts.

**Comment by DhanshreeA** [comment]
> @DhanshreeA , the conflicts happening at fetching are caused by [this method](https://github.com/ersilia-os/ersilia/blob/2a0ba90821f9226392df2bbc4dcfe1ab77306115/ersilia/serve/autoservice.py#L317). It is responsible for clearing temporary directories that match the prefix "ersilia-". However, since we are running multiple sessions simultaneously, one session may delete a temporary directory that the other session is still using, in this case, **/tmp/ersilia-749mg2go/docker_pull.log** which keeps the log of Image that was pulled from DockerHub for models running in a docker container.
> 
> The debug logger in the **clean_temp_dir** method only logs the directories it finds in the current session, so it doesn't detect or log directories created by other sessions. However, it still attempts to delete those directories if they match the "ersilia-" pattern, which is causing issues as other sessions are using them.
> 
> I was thinking of two ways this can be resolved, by using a model-specific or session-specific identifier to the temporary directories, though in a case where we are fetching the same model from different sources across multiple sessions, model-specific identifier will still run into the same resource conflicts. Let me know your thought regarding this.

Hi @Malikbadmus this is interesting - I feel like we can update the tmp directory prefix to include the session pid as well. You can get the session PID from `utils/session.py`. And then the deletion code can be made to delete the tmp directories only related to the session. What do you think?

**Comment by Malikbadmus** [comment]
> > @DhanshreeA , the conflicts happening at fetching are caused by [this method](https://github.com/ersilia-os/ersilia/blob/2a0ba90821f9226392df2bbc4dcfe1ab77306115/ersilia/serve/autoservice.py#L317). It is responsible for clearing temporary directories that match the prefix "ersilia-". However, since we are running multiple sessions simultaneously, one session may delete a temporary directory that the other session is still using, in this case, **/tmp/ersilia-749mg2go/docker_pull.log** which keeps the log of Image that was pulled from DockerHub for models running in a docker container.
> 
> > 
> 
> > The debug logger in the **clean_temp_dir** method only logs the directories it finds in the current session, so it doesn't detect or log directories created by other sessions. However, it still attempts to delete those directories if they match the "ersilia-" pattern, which is causing issues as other sessions are using them.
> 
> > 
> 
> > I was thinking of two ways this can be resolved, by using a model-specific or session-specific identifier to the temporary directories, though in a case where we are fetching the same model from different sources across multiple sessions, model-specific identifier will still run into the same resource conflicts. Let me know your thought regarding this.
> 
> 
> 
> Hi @Malikbadmus this is interesting - I feel like we can update the tmp directory prefix to include the session pid as well. You can get the session PID from `utils/session.py`. And then the deletion code can be made to delete the tmp directories only related to the session. What do you think?
> 
> 

Yes, I think this is the best way.

**Comment by DhanshreeA** [comment]
Refer to discussion here: https://github.com/ersilia-os/ersilia/issues/702#issue-1756694049 

This is actually expected behavior, and not a bug, at present.
