### ISSUE TITLE
🐕 Batch: Ersilia CLI Performance Improvement

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1299]
### Summary

@Abellegese is looking into improving the design architecture of core components within the Ersilia CLI, as well as replacing sequential execution with asynchronous approaches. 
On top of this this batch will be used to report results from benchmarking and profiling the current implementation, with reporting updates as we improve the architecture and implement asynchronous execution within flows.

**Comment by Abellegese** [comment]
The first objectives to improve performance on the Ersilia CLI are summarized below:

1) Improving performance of fetch command.
    -Looking for unnecessary  check ups, high latency interfaces, and asynchronizeable IOs
2) Improving performance of serve command.
    -On the preliminary level, this does not seem to have issues but I will look into ways to make it light (function stack calling is crazy everywhere).
3) Improving performance of run command.
    -This probably the most important CLI that needs performance improvement (speed mainly).
        -This command would be benefited from concurrency, async ops, high speed module binding and simplified 
         preprocessing steps.

The second objective is to improve performance on the IO operations on the global level.

1) Defining extensive IOs as async and concurency ops
2) Registering common IOs as singleton
3) Allowing template based Aync Ops creation with method specified on 2)
4) Module binding on ersilia command call is appeared to be some performance overhead, so making this fast on the global level


....Will continue as move on.

**Comment by Abellegese** [comment]
## Preliminary Report

**Fetch CLI**

I analyzed this command using **[py-spy and speedscope.app]**. The results shows that this command has a ton of unnecessary (**costly**) checkups.

**1)**  As @DhanshreeA  mentioned on issue #1259, the decision flow for model fetching appears to have high performance bottleneck.
      - I checked the network latency between the dockerhub and airtable during checkup and fetching, the airtable had 
         high network latency. 

This is the profiling results for original decision flow when model fetching (CPU time).
![original_deicision_flows](https://github.com/user-attachments/assets/4d57a249-2be3-4b01-9592-c95d10d28579)

And this is the simplified decision flow I tried to see how it goes.
![simplified_decision_flows](https://github.com/user-attachments/assets/f4480523-76f4-4083-8ca2-929b2bd9defa)

**Opinions**
------------------
In my opinion, I would use prior knowledge(Where each models are located and which models repos has high bandwidth or low latency, which was docker in my case) about the model repository and use that information and 
store it into a dictionary data structures (its fast in this case: key is model id and keys can be alist of info about the model). This dictionary can be used instead of the heavy checkups and loops.

**Comment by DhanshreeA** [comment]
> /approve

@aderemi1224 only maintainers have the permissions to dispatch approve workflows. 😅 And generally we want to run them on Model Request types of issues.

**Comment by DhanshreeA** [comment]
@Abellegese and @miquelduranfrigola honestly I am completely in favor of removing Airtable reads to fetch metadata. It is fine that we update Airtable when a model is submitted, but then we should continue to read only from S3 especially since Airtable gets dumped into S3 anyway. To make sure that the data is consistent across both, we could use webhooks instead of cron job as we are doing now.

**Comment by aderemi1224** [comment]
> > /approve
> 
> @aderemi1224 only maintainers have the permissions to dispatch approve workflows. 😅 And generally we want to run them on Model Request types of issues.

okay @DhanshreeA. Thank you so much

**Comment by Abellegese** [comment]
### Further Report on Fetch

I did further experiment and found the following results:

1) Standard example can be skipped cause the user check for themselves on the run command.
2) The DockerRequirement class performs several docker commands, one of them is **is_active() -is_working and the class itself**. The output response from the subprocess can be used as exception if docker is not active when pulling.
3) In ModelPuller -> pull -> is_available_locally() -> SimpleDocker ---this itself perform docker command that has performance cost.
   - is_available_in_dockerhub() -we can also use prior knowledge by registering image info in dictionary when pulled 
     then use that to show the status
4) In ModelRegister -> register() func we register twice-1) we register from dockerhub, 2) we register not from hosted and vice versa, dont get this one?
5) This is also not improvement but NotImplementation kind of bugs, in ModelDockerHubFetcher, we did not use those three functions
      - is_docker_installed
      - is_docker_active
      - is_available
   I dont know why? This functions use DockerRequirement?
6) Implemented concurent and normal asynchronous operation on 

`    async def fetch(self, model_id):
        # if not DockerRequirement().is_active():
        #     raise DockerNotActiveError()

        mp = ModelPuller(model_id=model_id, config_json=self.config_json)
        self.logger.debug("Pulling model image from DockerHub")
        await mp.async_pull()
        mr = ModelRegisterer(model_id=model_id, config_json=self.config_json)

        await asyncio.gather(
            mr.register(is_from_dockerhub=True),
            self.write_apis(model_id),
            self.copy_information(model_id),
            self.modify_information(model_id),
            self.copy_metadata(model_id),
            self.copy_status(model_id),
            self.copy_example_if_available(model_id)
        )`
pulling is also asynced.

### Overall

Measuring speed is quite tricky since it depend on several factors. But I performed repeated tests. Modifying the above specified improvements I got the result below:

On my internet speed and hardware, the docker pulling takes about ~45sec on average. The rest of the code after pulling takes about 35sec. 

The reduction in CPU time on the code on two improvement stage looks like below:

**Original code:**
![original](https://github.com/user-attachments/assets/212f5c2d-426f-41f6-8e58-22bf9897210b)

**Improvement one:**
![improvement-one](https://github.com/user-attachments/assets/768686cc-fe9d-47f6-816b-6a5238482eb3)

**Improvement two:**
![improvement-two](https://github.com/user-attachments/assets/5398ff0d-a6a7-4200-8859-98bb5ab49062)

### Conclusion
As we can see from the figures above, the code execution time reduced. If one can have better internet speed that affect the pulling, the overall fetch CLI can be improved.

**Comment by Abellegese** [comment]
## Preliminary Report

**Serve CLI**

The serve CLI has no significant overhead 😐.

**Comment by Abellegese** [comment]
## Preliminary Report

**Run CLI**

On the run command, I did a basic reverse engineering to get the api key,url and some other thing. I set the bench mark on the top of the main Ersilia run command objective, that is given input get computed output efficiently.

1) Assuming we have the correct smiles input and predefined free port, only need the code below to connect and get the result from the running container.

```python

import requests
import time
st = time.time()
url = "http://0.0.0.0:40937/run"
input = ({'key': 'NQQBNZBOOHHVQP-UHFFFAOYSA-N', 'input': 'C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]', 'text': 'C1=C(SC(=N1)SC2=NN=C(S2)N)[N+](=O)[O-]'},)
response = requests.post(url, json=input)
print(response.json())
et = time.time()
print(f"Normal API time: {et-st:.6f} second")

# Normal API time: 0.316354 second

**Comment by GemmaTuron** [comment]
Hi @Abellegese 

Thanks for the work and the detailed explanations. Do the merged PRs close this issue? If so please go ahead and close it.

**Comment by GemmaTuron** [comment]
Final refactoring of the CLI based on current discussions:
Catalog command:
- Catalog command should show a table by default. Consolidate --as-table / --as-json option
- Catalog command should show the identifier and slug by default when the --more option is not used
- Catalog --browser eliminate and consolidate --local/--hub
- Harmonize the --more flag: Identifier, Slug, Title, Task, Input shape, Output, Output shape, Model source (if local)
- --more flag picks up models from hosted_url when they have a URL even if they are actually in Docker
- Sort models by ID
- Index in the table to know how many models are there
Example command:
- Example models is not very clear, it should be only for the input
- Example -simple should have a header in the .csv file
Fetch command:
- when trying to fetch and docker is not active it does not give an informative error
