### ISSUE TITLE
🐛 Bug: Catalog command showing models in progress

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#1388]
### Describe the bug.

When I run `ersilia catalog --more` to see all available models, I get things like:
```
    {
        "Identifier": "eos9zfb",
        "Slug": null,
        "Title": "Ersilia Model In Progress"
    },
```
Where is the catalog command reading from? and of course models in progress should not be read.

### Operating environment

Ubuntu 22.04 LTS

**Comment by GemmaTuron** [comment]
I am giving this a high priority because the CLI commands should work without errors or small bugs like this one.

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron, the `ersilia catalog` [reads from S3 or AirTable](https://github.com/ersilia-os/ersilia/blob/6f879b5edbb1b034a73e352435da473b0018a3c4/ersilia/cli/commands/catalog.py#L91) by default, ie from the hub, if the flag `--local` is not specified. At present there is no filter on the response received from S3/AirTable either, and since the `--more` flag currently only displays three fields when getting this data from the hub, viz., 'Identifier', 'Slug', and 'Title', and not the 'Status' field it does not make sense to a filter unless we first increase the scope of the data fetched from the hub.

Regarding this particular model that appears in the result, I noticed that this is an archived [repository](https://github.com/ersilia-os/eos9zfb) with no clear explanation as to how or when this was created. I will delete this repository once we conclude this discussion. 

If you want to see all locally available models, you would need to use `ersilia catalog --local --more`. From a usability point of view, do you think you would benefit if we made reading local models a default behavior and reading from the hub optional, so you don't have to always use this flag?

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

Thanks for the explanation. I understand the catalog --local option, I am specifically speaking about the catalog command where all models are displayed. Is the S3/Airtable backend also containing "In progress" models? If so, there should indeed be a filter that leaves out the "In Progress" models so the user does not see them

**Comment by DhanshreeA** [comment]
Based on discussions, the local catalog and table formatting should be default.
