### ISSUE TITLE
🐛 Bug: Deciding to delete non-existing model

### ISSUE THREAD

**Issue by Abellegese** [ersilia-os/ersilia#1400]
### Describe the bug.

The delete cmd, when I tried to delete eos3b5e, the `needes_delete` considered that the image or model existed and considered it as it needs deletion, but the model was not there, its folder on both `des`  and `repo` . 

### Operating environment

Ubuntu LTS

**Comment by Abellegese** [comment]
First time I ran the command and it was successfull, but when I delete same model again it says successfully deleted, and that need delete function was also True. But infact image, eos folder was mot there for the model if that makes sense.

**Comment by DhanshreeA** [comment]
Thanks @Abellegese - that is somewhat making sense, however I need further clarity. Can you help me with the exact steps I could run to reproduce this? Thanks!

**Comment by DhanshreeA** [comment]
@Abellegese is it somewhat related to [this](https://github.com/ersilia-os/ersilia/issues/1395) by any chance?

**Comment by DhanshreeA** [comment]
Hi @Abellegese I am still having trouble reproducing this, for example, this is what I see:

<img width="573" alt="Screenshot 2024-11-27 at 17 44 19" src="https://github.com/user-attachments/assets/84c14da7-2221-4192-8b8c-ab579f68ba8c">

I fetched eos3b5e, as you can see through the catalog output, and it has its corresponding folders in the dest and repository directories. I then deleted it, and it got successfully deleted, and then I deleted it again which raised an error, as you can see.

**Comment by GemmaTuron** [comment]
Hi @Abellegese 
I am also unclear as to what you mean by this sentence: Again try to delete it even its not there. Then its still consider it successfully deleted.

Is it that you do the same procedure that @DhanshreeA is showing but then instead of saying `No delete is necessary` it shows a `model deleted successfully` message? Have you checked you are running the latest ersilia version and everything? And can you paste a screenshot of the error?

**Comment by Abellegese** [comment]
Am figuring this out Gemma.
