### ISSUE TITLE
Collect all the steps required to run the model

### ISSUE THREAD

**Issue by honeyankit** [ersilia-os/ersilia#302]
Collect steps for to executing the Ersilia model

Exit Criteria:
Capture all the steps required for Ersilia to execute the model and generate the prediction values.

**Comment by honeyankit** [comment]
Based on the demo video below are the steps used by Ersilia to run the model:
1. `ersilia fetch` command will fetch the model from the git repository.
2. `ersilia serve <model name>` will pick a model.  
3. `ersilia sample <model name> -f input.csv -n 100` will run the model for 100 molecules provided in the input file.
4. `ersilia api calculate -i <input.csv> file -o <output.csv>` file. 


Note
-------------------------------------------------------------------------------------------------------------------------
- Molecule is the input to the models.
- Molecule and its prediction values are the output from the table.

**Comment by honeyankit** [comment]
@miquelduranfrigola Could you confirm the above steps are correct? Also could you upload a very small input.csv file and output.csv here as well?

**Comment by GemmaTuron** [comment]
Hi @honeyankit,

Command 4, api, depends on the model. Most of them use a "predict" api, so:
`ersilia api predict -i <input.csv> -o <output.csv>`

I am attaching an example I got with the following commands:
`ersilia fetch eos2ta5`
`ersilia serve eos2ta5`
`ersilia api predict -i input_test.csv -o output_test.csv`

If you do not specify the output file it will just print the result in the screen in .json format.

[input_test.csv](https://github.com/ersilia-os/ersilia/files/9751709/input_test.csv)
[output_test.csv](https://github.com/ersilia-os/ersilia/files/9751710/output_test.csv)

**Comment by miquelduranfrigola** [comment]
Thanks for all of this.

The only command that is missing at the moment in ersilia is `ersilia sample`. We do have a command called `ersilia example` which works similarly. The idea of the sample command would be that it would query the existing precalculated data and then provide a sample of molecules that have not yet been calculated. We will be able to provide this functionality as soon as we have a database in AWS, most likely DynamoDb.

As for the APIs - indeed, the API names may vary. The command `ersilia api -i input_test.csv` (without `calculate` or `predict`) is more general, since it automatically selects the available API, without specifying the name.

**Comment by honeyankit** [comment]
@miquelduranfrigola @GemmaTuron : Are these the [models repos](https://github.com/orgs/ersilia-os/repositories) thats needs to be fetched?

**Comment by honeyankit** [comment]
> ersilia api -i <input.csv> file -o <output.csv> file.

Most model have only one api.

**Comment by miquelduranfrigola** [comment]
Hi @honeyankit. I am now working on the `sample` command. Currently, it is not available. I will keep you updated.

**Comment by miquelduranfrigola** [comment]
Hi @honeyankit the `sample` command is now finished. Based on this command, I suggest the following workflow:

```
MODEL_ID=$(ersilia sample --model)
ersilia fetch $MODEL_ID
ersilia serve $MODEL_ID
ersilia sample -n 100 -f input.csv
ersilia api -i input.csv -o output.csv
ersilia close
```
