### ISSUE TITLE
🐛 Bug: Apps crash randomly on newly installed ubuntu 22.04.

### ISSUE THREAD

**Issue by zheeburg** [ersilia-os/ersilia#311]
### [Apps crash randomly on newly installed ubuntu 22.04.

[Apps crash randomly on newly installed ubuntu 22.04
I've just installed Ubuntu 22.04 on my laptop with 8GB ram (no dual boot, ext4 + 20GB linux swap);

Installed 2 gnome shell extensions (Dash to panel, Workspace Matrix);

My working environment is just vs code, webpack dev server, and chrome;

During the active development something dies ~ every 10 minutes. Could not find any error logs, it looks like app is closed (in case of webpack dev server the terminal window is closed). If it's chrome - no chrome processes left.

For now, it did not happen with the active app - only background ones die. It's like you save a code, switch to the browser - and there's no browser, or you inspect something in devtools, switch to vs code - and there's no vs code.

What should be the first step investigating this? Where to look for any logs/crash reports?

### Operating environment

ubuntu 22.04

**Comment by GemmaTuron** [comment]
Hello @zheeburg,

This is not an issue with Ersilia so I will close this issue as it is not related to the code in this repository

I guess you have copied the information from this thread? https://askubuntu.com/questions/1408784/apps-crash-randomly-on-newly-installed-ubuntu-22-04#:~:text=Since%20apps%20crash%20with%20less,programs%2Ftabs%2C%20etc).

I can't provide much support as I am not an ubuntu expert, this has to do with your system installation. Perhaps try Ubutnu 20.4 ¿
