### ISSUE TITLE
📑 Feature Request: Improve documentation for Ersilia Installation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#318]
### Is your feature request related to a problem? Please describe.

As more users test Ersilia, different computer system configurations might give issues.

### Describe the solution you'd like.

Update documentation so new users know where to start debugging

### Additional context.

This is related to Issue #308

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya can you provide two sentences describing the problem you encountered with the antivirus and how to solve it? I'll then add it to Ersilia's docs

**Comment by GemmaTuron** [comment]
And @zheeburg could you do the same for the memory issue? 
Please both mention your system installation, the problem you encountered and how you solved it.

**Comment by shenyuygoodness** [comment]
@GemmaTuron please I will really love to contribute to this issue but i do not know in what particular way to go about it. Please can you assign me to a task(s).

**Comment by ZakiaYahya** [comment]
> Hi @ZakiaYahya can you provide two sentences describing the problem you encountered with the antivirus and how to solve it? I'll then add it to Ersilia's docs

Yes sure.

**Comment by ZakiaYahya** [comment]
> > Hi @ZakiaYahya can you provide two sentences describing the problem you encountered with the antivirus and how to solve it? I'll then add it to Ersilia's docs
> 
> Yes sure.
When i tried fetching ersilia model in WindowSubSystem(WSL) with ubuntu 18.04 , then somewhere while installing dependancies my windows crashes. This happens because of Antivirus that blocks the WSL to install some dependencies in ubuntu folder created in your windows. So, i resolved this issue by uninstalling the Antivirus for time being and everything works fine .

**Comment by alaminumar** [comment]
Hello @GemmaTuron , i would like to contribute to the documentation. When i tried running Ubuntu after i installed it, it did not work. This is because i use Windows 10 Home. Hyper v is used for virtualization, but it is not installed in Home and Pro versions. Follow this article step by step to install and enable it . https://www.itechtics.com/enable-hyper-v-windows-10-home/

**Comment by GemmaTuron** [comment]
thanks @ZakiaYahya and @alaminumar 
@shenyuygoodness this issue is assigned once contributors run into an issue when installing ersilia or downloading a model, you can check more about the contribution guidelines [here](https://ersilia.gitbook.io/ersilia-book/contributors/internships/outreachy-winter-2023)

**Comment by shenyuygoodness** [comment]
Understood
Will revisit the guide at once

**Comment by pauline-banye** [comment]
Hi @GemmaTuron, I had an issue activating `conda activate ersilia` on prerequisite 5, using the instructions on the [Ersilia Installation](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/installation) documentation. 

I eventually figured out that it was because Ersilia had not been installed at this point. Might I suggest that the  instructions on **Pre-requisite 5: The Isaura data lake** be placed after **2.2. Install Ersilia** to avoid any mixup for new contributors?

**Comment by Malikbadmus** [comment]
> > > Hi @ZakiaYahya can you provide two sentences describing the problem you encountered with the antivirus and how to solve it? I'll then add it to Ersilia's docs
> > 
> > 
> > Yes sure.
> > When i tried fetching ersilia model in WindowSubSystem(WSL1) with ubuntu 18.04 , then somewhere while installing dependancies my windows (10 pro) crashes. This happens because of Antivirus that blocks the WSL to install some dependencies in ubuntu folder created in your windows. So, i resolved this issue by uninstalling the Antivirus for time being and everything works fine .

Hello @ZakiaYahya , if I may add, you could probably add the WSL file to the exceptions of your Anti-virus program instead of uninstalling the program outright.

**Comment by GemmaTuron** [comment]
Hi all,

I have realised this will be very important for future users and therefore we should collect this information in a more ordered manner. I have opened an issue #359  where you can complete the information in a specific format, which will make it much easier to collect the information.
I'd really appreciate if you can move your comments there @ZakiaYahya @alaminumar @pauline-banye @Zainab-ik @Malikbadmus @zheeburg 
Many thanks!

(I will close this issue to avoid information duplication)

**Comment by zheeburg** [comment]
Yes sure

**Comment by zheeburg** [comment]
Operating System:  Linux Ubuntu 20.4 LTS 

Conda Version:  conda 22.9.0  

Python Version:  Python 3.9.12 

Issue:  My windows crashes and restarted, stopping all active processes whenever i fetch the ersilia model.

How did you solve it: 
It turned out that [systemd-oomd](https://manpages.ubuntu.com/manpages/jammy/en/man8/systemd-oomd.8.html) (a userspace out-of-memory (OOM) killer) was killing my applications whenever I was running low on swap space.

You can run the following command to see if it is the case for you as well:
`journalctl -u systemd-oomd`
Two options:

1. Disable systemd-oomd: systemctl disable --now systemd-oomd
2. [Increase swap size](https://askubuntu.com/a/1177939/59479) (recommended).
