### ISSUE TITLE
🐛 Bug: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by muskansawa** [ersilia-os/ersilia#321]
### Describe the bug.

It fetches the model , after the fetch is completed it asks for password and then there is a traceback error every time , it also says :
`The operation couldn’t be completed. Unable to locate a Java Runtime that supports ap`
 but i did install JAVA jdk from oracle. 

it also has a type error in the end

### Describe the steps to reproduce the behavior

1. activate the ersilia environment
2. run : ersilia -v fetch  eos2re5

### Expected behavior.

should fetch the model for me

### Screenshots.

<img width="768" alt="Screenshot 2022-10-12 at 12 19 37 PM" src="https://user-images.githubusercontent.com/44108897/195270418-954ae827-8459-4b07-ba4b-acb581aa5f3e.png">

i have also found this error message:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/44108897/195270840-4d979f7b-a6e2-4185-ae7a-6c26c8e31681.png">

in the end it gave traceback error of module not found 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/44108897/195296028-f7feb3d4-dc5d-4b00-b9d4-d489c06e4f9f.png">

### Operating environment

macos 12.6

### Additional context

i have python 3.9.12 installed

P.S. these commands work fine for me :
ersilia --help
ersilia catalog

**Comment by risper25** [comment]
Hi @muskansawa, do you have docker installed?

**Comment by Zainab-ik** [comment]
I also encounter the same error while running the dummy model with the `ersilia -v fetch eos3b5e
ersilia serve eos3b5e` model and I've been unable to run the model.  @GemmaTuron

**Comment by AnneO1** [comment]
I successfully installed ersilia until encountered same error while running the dummy model. 
On `ersilia -v fetch eos3b5e` i got these warning:

![ersilia -v fetch eos3b5e warningerror](https://user-images.githubusercontent.com/115647922/195398240-8bdbd859-6d26-4212-a29d-4121ac03d13a.PNG)

On `ersilia serve eos3b5e` i got the error:

![ersilia serve eos3b5e erroroutput](https://user-images.githubusercontent.com/115647922/195398438-c74d4446-2954-4801-8df8-60b9c23ec341.PNG)

**Comment by GemmaTuron** [comment]
Hello @muskansawa !

This model is quite particular because it requires python 2.7. I thought we had solved this issue but apparently not. Don't worry about this model and skip it for the moment, I need to think how to go about this error.

@Zainab-ik and @AnneO1 please open a bug with the model name, your error as you can see is not related to the error  @muskansawa was having, check the screenshots and you will see different outputs.
It will be easy to debug if you open an issue withthe specific  log of the model error.
I'll close this issue for model eos2r5e
