### ISSUE TITLE
🐛 Bug: EmptyOutputError: Model API eos46ev : predict did not produce an output.

### ISSUE THREAD

**Issue by alaminumar** [ersilia-os/ersilia#322]
### Describe the bug.

when i try to fetch eos46ev from the CLI it gives me an EmptyOutput Error. 

### Describe the steps to reproduce the behavior

1 activate ersilia 
2 run ersilia -v fetch eos46ev

### Expected behavior.

fetch the model

### Screenshots.

![Screenshot (85)](https://user-images.githubusercontent.com/110132616/195350082-f3489705-cd0e-4864-807d-0c6a8b00c80e.png)

### Operating environment

Ubuntu 20.04 LTS

**Comment by GemmaTuron** [comment]
Hi @alaminumar 
Let me explain a bit about this error. At fetching time, Ersilia tests 3 molecules to be sure the model works (you can see them printed in your screen as key and input). The result you should get there is:
`19:00:45 | DEBUG    | [{'input': {'key': 'LUHMMHZLDLBAKX-UHFFFAOYSA-N', 'input': 'CC1C2C(CC3(C=CC(=O)C(=C3C2OC1=O)C)C)O', 'text': 'CC1C2C(CC3(C=CC(=O)C(=C3C2OC1=O)C)C)O'}, 'output': {'probability': 0.20360326385165065}}, {'input': {'key': 'QRXWMOHMRWLFEY-UHFFFAOYSA-N', 'input': 'C1=CN=CC=C1C(=O)NN', 'text': 'C1=CN=CC=C1C(=O)NN'}, 'output': {'probability': 0.8622619164180295}}]`

(I just ran it). You can see how I get a numeric probability instead of a None. I see two reasons why this is happening:

- Model fetching failed at some point above but the error is not informative
- Ersilia is not properly installed (did you have the same with other models?)

I am tagging @miquelduranfrigola here to see if he can provide some more guidance

**Comment by ZakiaYahya** [comment]
@GemmaTuron @alaminumar i'm getting the same error while fetching ersilia model eos526j. 
![Model_eos56j_Error](https://user-images.githubusercontent.com/54974236/195437527-4b3222c6-8db4-4fae-b7b2-c0e1ed10836f.png)

and @GemmaTuron i don't think this is due to "ersilia not properly installed" because i fetch and predicted assigned ersilia model eos2v11 successfully, if the ersilia is not installed properly then other models and the dummy model also through this error while fetching

**Comment by alaminumar** [comment]
@ZakiaYahya have you solved the issue ? I tried doing it with a different model , it ran for 2 and a half hours only to give me the same error

**Comment by GemmaTuron** [comment]
Hi @alaminumar  and @ZakiaYahya are you sure you have Git-LFS installed? this is a common error :)

**Comment by Zainab-ik** [comment]
I happened to have same error with model eos4tcc, I got the key and input results also. 
@ZakiaYahya @alaminumar , have you been able to resolve it?


@GemmaTuron , I have git LFS installed

**Comment by alaminumar** [comment]
@Zainab-ik unfortunately not yet

**Comment by Malikbadmus** [comment]
Hi @Zainab-ik and @alaminumar, I also encountered this error while i was fetching model eos157v.  see issue  #295 on how we resolve this.

**Comment by ZakiaYahya** [comment]
> Hi @alaminumar and @ZakiaYahya are you sure you have Git-LFS installed? this is a common error :)

Yes when i saw the log, it has error refering gif-lfs, although i had installed it while installing ersilia hub but still the conda environment didn't recognize it somehow. so, i installed tha git-lfs again in conda environment using 
conda install git-lfs -c conda-forge
git-lfs install
and rerun the model again and it runs successfully. @alaminumar @Zainab-ik go through your log history and see if your error occurs due to git-lfs, reinstall it again, close the terminal, open it again and rerun the model.

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya thanks, very helpful. Git-lfs is sometimes tricky to install.

@Zainab-ik and @alaminumar please share the FULL logs of the error so I can provide guidance. (use the flag `> my.log 2>&1` at the end of your CLI)

**Comment by Zainab-ik** [comment]
> Hi @ZakiaYahya thanks, very helpful. Git-lfs is sometimes tricky to install.
> 
> @Zainab-ik and @alaminumar please share the FULL logs of the error so I can provide guidance. (use the flag `> my.log 2>&1` at the end of your CLI)

@GemmaTuron
`model eos4tcc`, [https://drive.google.com/file/d/1slnDmcMm4oo3Nj1JcCf8wi5Eee0KoTyk/view?usp=sharing](url) this is my log file

**Comment by Zainab-ik** [comment]
I think i should open a new issue since it's different model but similar error

**Comment by Zainab-ik** [comment]
> I think i should open a new issue since it's different model but similar error

I'm getting a new error 

> NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43a46ed910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

not the error above again.

**Comment by miquelduranfrigola** [comment]
Gemma is this solved?
