### ISSUE TITLE
🐛 Bug: TyperError while using predict api

### ISSUE THREAD

**Issue by Femme-js** [ersilia-os/ersilia#326]
### Describe the bug.

The model eos2gth was fetched and served successfully, but a TypeError is being raised while predicting with the model.

### Describe the steps to reproduce the behavior

>>  ersilia -v fetch eos2gth
>> ersilia -v serve eos2gth
>> ersilia -v api predict -i eml_canonical -o eos2gth_out.csv

### Expected behavior.

Model test run successfully

### Screenshots.

![Screenshot from 2022-10-13 09-17-38](https://user-images.githubusercontent.com/48143381/195494692-26779dc0-7e9c-4962-97bd-3f5c1f447a1b.png)

### Operating environment

Ubuntu 18.04.3 LTS

**Comment by Zainab-ik** [comment]
@Femme-js , can you indicate the model ID in your title for easy identification incase someone has same error.

**Comment by GemmaTuron** [comment]
Hi @Femme-js 

The problem here seems that you are missing the input file name, which should be `eml_canonical.csv`
On your issue I see only `eml canonical` without the .csv

Also make sure you are either on the folder where eml canonical is stored, or you are adding the path in the input, for example in my case it would be something like that (if I was doing the test on a folder in my Desktop, and I was running commands from the Desktop):

```
(ersilia) gturon@sotira: cd Desktop
(ersilia) gturon@sotira:~/Desktop$ ersilia -v api predict -i "test/eml_canonical.csv" -o "test/eos2gth_eml.csv"

```

**Comment by Femme-js** [comment]
Hi @GemmaTuron ! I missed out this silly mistake. Thanks for your help.

In case someone had the same error, model ID is eos2gth
