### ISSUE TITLE
🐛 Bug: Fetching model eos54ij with "EmptyOutputError"

### ISSUE THREAD

**Issue by RoseZhen2022** [ersilia-os/ersilia#386]
### Describe the bug.

Fetching model eos54ij failed with error message "EmptyOutputError". Using Colab to fetch this model also got this error message.

### Describe the steps to reproduce the behavior

ersilia -v fetch eos54ij > eos54ij.log 2>&1

### Expected behavior.

fetch the model succeffully

### Screenshots.

file:///home/ru/Documents/ersilia/eos54ij.log

### Operating environment

Ubuntu 22.04.1 LTS

**Comment by RoseZhen2022** [comment]
[eos54ij.log](https://github.com/ersilia-os/ersilia/files/9817732/eos54ij.log)
Here is the log file.

**Comment by GemmaTuron** [comment]
Thanks @RoseZhen2022 !
I can confirm the error is reproducible, whereas this model was working a few weeks ago. This is probably due to the update of a package.
We will dig deeper and come back to this when I have a better understanding of what might be happening!
Leave the issue open and mark this in purple on excel. Have you tested the model in colab?
Attaching here my log file to keep track:
[eos54ij.log](https://github.com/ersilia-os/ersilia/files/9822606/eos54ij.log)

**Comment by RoseZhen2022** [comment]
> Thanks @RoseZhen2022 ! I can confirm the error is reproducible, whereas this model was working a few weeks ago. This is probably due to the update of a package. We will dig deeper and come back to this when I have a better understanding of what might be happening! Leave the issue open and mark this in purple on excel. Have you tested the model in colab? Attaching here my log file to keep track: [eos54ij.log](https://github.com/ersilia-os/ersilia/files/9822606/eos54ij.log)

Thank you for your reply. Actually, I have run this model on Colab, and I got the same result. It was fetched failed. Do I need to open a new issue about Colab result?

**Comment by GemmaTuron** [comment]
No that's fine, I'll flag the model on our system for checking.
I leave the issue open to report updates!

**Comment by angelnagaba** [comment]
Hello @GemmaTuron I am trying to test this same model with this  error. Can i as well flag it purple

**Comment by GemmaTuron** [comment]
I will close this issue due to inactivity
This model works both in WSL and Google colab currently
