### ISSUE TITLE
🦠 Model Request: cyp3a4 - veith

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#432]
### Model Title

Cyp3a4 (TDC dataset)

### Publication

Hello @cee-tech21!

As part of your Outreachy contribution, we have assigned you the dataset "cyp3a4" from the Therapeutics Data Commons to try and build a binary classification ML model.
Please copy the provided Google Colab template and use this issue to provide updates on the progress. We'll value not only being able to build the model but also interpreting its results.

**Comment by Cee-tech21** [comment]
Quick local implementation of this task has been initiated. Implementation will also be mirrored/advanced on colab

### From TDC

> **Task Description:** Binary Classification. Given a drug SMILES string, predict CYP3A4 inhibition.
> CYP3A4 is an important enzyme in the body, mainly found in the liver and in the intestine. It oxidizes small foreign organic molecules (xenobiotics), such as toxins or drugs, so that they can be removed from the body.

**Comment by Cee-tech21** [comment]
A model was trained using the default settings of the Lazy-QSAR package. The original dataset was split into three groups or samples to use for

1. training of a machine learning learning model, 
2. validation of the trained model 
3. testing of the trained machine learning model.

Some metrics were used to gauge the performance of the trained model

**Comment by Cee-tech21** [comment]
The consistent predictions of our trained model implies successful training. However, the model needs to be finetuned -- in order to improve the values (increase percentage) of the precision and the recall metrics. Future training will specifically alter the machine learning models/parameter (e.g. XGBoost, Random Forest) to see how this impacts prediction capacity. Additionally, the training data may be further sampled to ensure equal size of the class groups (balance) in the training data.

**Comment by GemmaTuron** [comment]
Hi @Cee-tech21 

Please revise the input you are passing to the ROC curve, amend it and then you can go onto closing the issue and moving to work in your final contribution

**Comment by GemmaTuron** [comment]
Hello @Cee-tech21  !

Thanks for your contributions to Ersilia during the Outreachy Application Period! We hope you have learnt and enjoyed as much as the Ersilia team did!
I will close this issue as this was part of the application period solely.
