### ISSUE TITLE
Enhancement of README.file

### ISSUE THREAD

**Issue by manognyaa** [ersilia-os/ersilia#49]
**Is your feature request related to a problem? Please describe.**
The readme file is absolutely stunning. When I was reading the file, it seems to be very simple, the alignments, bold fonts,etc. I would like to add my creativity.

**Describe the solution you'd like**
I will change the file look by adding some outstanding ideas on to it.
@GemmaTuron could you pls assign this to me

**Describe alternatives you've considered**

**Additional context**

**Comment by GemmaTuron** [comment]
Hi @manognyaa 

Thanks for your enthusiasm. Issue #11 is addressing this task. There are currently 10 people assigned to it but we will soon open it to more, we just need to set up the structure so that we can review all your suggestions. May I ask you to keep thinking of what you want to add but wait a couple of days to upload it?

**Comment by manognyaa** [comment]
> Hi @manognyaa
> 
> Thanks for your enthusiasm. Issue #11 is addressing this task. There are currently 10 people assigned to it but we will soon open it to more, we just need to set up the structure so that we can review all your suggestions. May I ask you to keep thinking of what you want to add but wait a couple of days to upload it?

oh yes, thanks for the reply. I will be eagerly waiting for this issue. thank you !

**Comment by miquelduranfrigola** [comment]
Closing this issue now! Thanks for a great discussion and stay tuned!
