### ISSUE TITLE
[Task] Add dummy LFS object in template repo

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#536]

**Comment by GemmaTuron** [comment]
Actually we found out that Git-LFS does not work in GitHub templates, so we need to create a workaround and incorporate the Git-Lfs object afterwards.
The goal is to have a dummy git-lfs object in the eos-template so that contributors can fork the repository and push LFS objects (requires the repo to ALREADY have an LFS object)

**Comment by D1M1TR10S** [comment]
Templates can't have Git LFS objects. Tack this onto the end of the approve workflow.

Git-LFS is a paid feature, but there's a super discount applied. Won't be charged in the foreseeable future.

They need to have the model approved in order to get to this step – for new model submissions.

**Problem:** For any forks from a repository being uploaded to a repo, the fork will still trigger Git-LFS. Could burn down the entitlements for Git-LFS.
=> If workflow adds Git-LFS to a repo the org is charged. Can fork the repo and use the repo for whatever they want, and Ersilia will be billed for it. Ask the Git-LFS team about this to see if there's a workaround.

If someone forks and merges, can we delete that repo? => No. The person forking owns it.

Each model repo has a folder called "model" which has checkpoints for the model. They can sometimes be a couple of gigabytes with parameters of the models. Could store this separately in a package, but to keep everything centralized we decided to use Git-LFS. If we offer Git-LFS in public repos they can be abused.

**Next steps:**
- [ ] Ask @vtbassmatt about this

**Comment by vtbassmatt** [comment]
> **Problem:** For any forks from a repository being uploaded to a repo, the fork will still trigger Git-LFS. Could burn down the entitlements for Git-LFS. => If workflow adds Git-LFS to a repo the org is charged. Can fork the repo and use the repo for whatever they want, and Ersilia will be billed for it. Ask the Git-LFS team about this to see if there's a workaround.
> 
> If someone forks and merges, can we delete that repo? => No. The person forking owns it.

If someone starts abusing your LFS entitlement, Support has tools which can help. The bad fork can be forcibly detached and the orphan objects in your network can be pruned.

**Comment by GemmaTuron** [comment]
Add an action in: https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/approve-dispatch.yml
after line 66

**Comment by D1M1TR10S** [comment]
Is it possible to detach the fork from the parent organization so they're aren't consuming Ersilia's Git LFS entitlements whenever someone forks a repo. By default there's 50 GB free, and no model should be that big.

**Comment by vtbassmatt** [comment]
GitHub Support can help you detach a repo if needed.

Also, heads up: the free entitlement is [1GB](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage), not 50GB.

**Comment by GemmaTuron** [comment]
Thanks @vtbassmatt !

@GrantBirki we have tried to add the dummy lfs file as discussed in the[ approve-dispatch](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/approve-dispatch.yml) workflow but we are unable to make the commit to the repo because we don't have permissions. We are trying to run it from ersilia-bot with the https://github.com/actions-js/push but it seems we are unable to reset the author to our bot:
`remote: Permission to ersilia-os/eos5iod.git denied to github-actions[bot].`

Do you have any suggestion?

**Comment by miquelduranfrigola** [comment]
Hi all!

**Update**: we have managed to make it work. The workflow is probably not very clean (we are just learning...) but it does what we expect it to do now. In brief, it tracks as `mock.csv` file with LFS and then it commits the changes to the newly created repo.

As an example you can see this repository: https://github.com/ersilia-os/eos5ixa

We now need to check that this behaves as expected when users fork the repo and track new files with Git LFS. We will keep you posted!

**Comment by miquelduranfrigola** [comment]
When I fork to my username: https://github.com/miquelduranfrigola/eos5ixa I am indeed able to add *new* Git LFS objects. So it looks very promising! We will ask someone who is not an `ersilia-os` owner to try it.
