### ISSUE TITLE
Output adapter serialize JSON to CSV

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#560]
Hello @carcablop !

Based on previous discussion, it will be good to serialize JSON outputs to CSV. @DhanshreeA has already investigated the issue a little bit. I have assigned it to you because you have expressed interest in it: #371

A while ago, I wrote some code that can help:
1. https://github.com/ersilia-os/ersilia/blob/master/ersilia/io/dataframe.py
2. https://github.com/ersilia-os/ersilia/blob/master/ersilia/io/output.py
3. https://github.com/ersilia-os/ersilia/blob/master/ersilia/utils/csvfile.py
4. https://github.com/ersilia-os/ersilia/blob/master/ersilia/serve/schema.py

In particular, in (2) there is a `DictlistDataframeConverter` that can help. In (3), there is a very simple CSV dataloader that we could extend. Finally, in (4) we could consider writting something like `def _is_csv_serializable(...)` to check whether a given output could be expressed in a CSV (the majority of outputs will be thanks to the JSONL format as discussed)

I would suggest that we organize a 1-1 meeting to talk about this and then we reflect the strategy in this issue thread.

**Comment by carcablop** [comment]
Hello @miquelduranfrigola. 
Thank you very much for this information, it is really valuable for me. I'll talk you by slack to organize the meet.

**Comment by carcablop** [comment]
Hi @GemmaTuron and @miquelduranfrigola 

A possible solution that was proposed was the following:
Considering JSONL format, it is intended to write all the output of the JSON file in a single column. To make sure that this implementation won't fail because the outputs can be variable with respect to the length of the tree in the JSON. It is proposed to implement a function that can read the model output from the airtable, and if that output is JSON we can implement the solution with the JSONL format. For this, the following must be taken into account:

1. Predefine the types of outputs, to create a column that can be called output_shape, where the type of output for each model is defined. Which can be:
- Multiple columns
-single
-JSON.

2. Implement the function to read from the airtable the output (the previously created column "output_shape") given a model.

3. Modify the function to_data_frame() : Depending on the output of the output_shape, if it is JSON, the JSONL format functionality is executed, and for other types of outputs it is executed as it was done before.

**Comment by carcablop** [comment]
Hello @GemmaTuron  and @miquelduranfrigola.

As stated above, I've been working on this problem using the JSONL format to serialize the JSON output to a csv.
 I was working on the implementation of the function that allows reading the output of the "output shape" field from the airtable, if it is an output shape equal to "Flexible list" (which is the case of the eos526j and eos5qfo models, with JSON output type ), we serialize the output to a string, and return the entire JSON string in a single column of the csv file.
I have tested the eos526j model in my Cli, with a .csv type input file with two molecules and specifying the .csv file output. It runs without errors. I attach the output: 
[ouput_eos526j.csv](https://github.com/ersilia-os/ersilia/files/10680099/ouput_eos526j.csv)
I'm still testing the functionality by passing the entire "eml_canonical.csv" file as input, but this takes a long time. (It's still running.)

I also ran the eos5qfo model, which also presented issues, this model runs on my machine successfully with the changes and I have also been able to have the output with the .csv extension successfully passing the eml_canonical as input. I attach the output for this model: 
[output_eos5qfo_1.csv](https://github.com/ersilia-os/ersilia/files/10680108/output_eos5qfo_1.csv)

As you can see in the output file, let's return all the JSon in a single column named "outcome".

I only have to make sure that the models that have tested for me successfully continue to test successfully in my CLI with the changes before opening a pull request.

**Comment by carcablop** [comment]
Hi @miquelduranfrigola 
After trying to make the predictions for a few hours, the model throws the following error, indicating that the connection has been lost. 
[log_predict_eos526j.txt](https://github.com/ersilia-os/ersilia/files/10681013/log_predict_eos526j.txt)

**Comment by GemmaTuron** [comment]
Hi @carcablop 

This error is due to internet issues, not related to the Hub. have you tried again?

**Comment by GemmaTuron** [comment]
Hi @carcablop 

Following up on this to make sure we close the issue during this week

**Comment by carcablop** [comment]
Hi @GemmaTuron 
This model usually takes a long time to run, and possibly it was an internet connection problem, I'm going to run it again.

**Comment by ana42742** [comment]
Hi @carcablop! Any updates?

**Comment by carcablop** [comment]
This is the pull request:
https://github.com/ersilia-os/ersilia/pull/654

**Comment by GemmaTuron** [comment]
Hi @carcablop !

This is fantastic thanks for solving that

**Comment by GemmaTuron** [comment]
I will close this issue!
