### ISSUE TITLE
🦠 Model Request: Incorporating SciSpacy Into Ersilia Model Hub

### ISSUE THREAD

**Issue by Femme-js** [ersilia-os/ersilia#562]
### Model Name

SciSpacy

### Model Description

scispaCy is a Python package containing spaCy models for processing biomedical, scientific or clinical text.

### Slug

scispaCy-biomedical-text-processing

### Tags

entity extraction, AbbreviationDetector, Hearst Patterns, EntityLinker

### Code

https://github.com/allenai/scispacy

### License

 Apache-2.0 license

**Comment by miquelduranfrigola** [comment]
Thanks @Femme-js this model is interesting and, as you mentioned in our online meeting, it is straightforward to incorporate with SpaCy.

As discussed, let's leave this one on-hold because, at the moment, the priority is to obtain text *embeddings*, and it doesn't seem to be straightforward with SciSpaCy.

As soon as we need named entity recognition or other related task, we will certainly retake this model.

**Comment by GemmaTuron** [comment]
I will close this request because it remains out of the scope of the current version of the Hub
