### ISSUE TITLE
🐛 Bug: bentoml 0.11 won't download if previously installed on computer 

### ISSUE THREAD

**Issue by pittmanriley** [ersilia-os/ersilia#720]
### Describe the bug.

Miquel and I worked through an issue found when downloading the Ersilia model hub. I was getting an error saying `ModuleNotFoundError: No module named 'bentoml.cli'` when I tried to use any of the Ersilia commands.

### Describe the steps to reproduce the behavior

1. conda activate ersilia
2. git clone https://github.com/ersilia-os/ersilia.git
3. cd ersilia 
4. pip install -e .
5. ersilia --help  OR ersilia catalog OR any other ersilia command 

### Expected behavior.

During the installation process, bentoml should be automatically downloaded in the 0.11 version regardless if bentoml was already installed on the computer, but we found that if it is already downloaded, this won't happen. The code needs to be updated to check to see if bentoml is version 0.11 rather than just checking if it is already downloaded. 

### Operating environment

macOS 12.3.1

**Comment by miquelduranfrigola** [comment]
Thanks @pittmanriley 

The issue was caused by `bentoml` already being installed, which causes the `is_installed()` method in the `BentoMLRequirement` class to return `True` in the `setup.py` script.

The solution is to check for the actual [version of BentoML maintained by Ersilia](https://github.com/ersilia-os/bentoml-ersilia), instead of `is_installed`. I have added an `is_ersilia_bentoml` method to the `BentoMLRequirement` class.
