### ISSUE TITLE
Delete stuck models

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#731]
Over the last two years of building the Hub, there are a few models that have been abandoned halfway, either because the contributors moved onto something else, the models were too difficult or we estimated they were not relevant. 
But all of them have repositories open, and we should either finish them or delete them, to avoid dragging unfinished elements. Here is a comprehensive list, can we open a public discussion and decide what to do with each one?

- [ ] eos1086: embeddings-extraction
- [ ] eos3sa2: fs-mol-protonet
- [ ] eos5y9f: molpmolfit
- [ ] eos3d3r: cardpred
- [ ] eos1amn: pmapper-3d-pharmacophore
- [ ] eos8fth redial-2020
- [ ] eos1bba gem-representation-learning
- [ ] eos5ecc iupac2smiles

**Comment by GemmaTuron** [comment]
A priori, I'd try to finish eos8fth and eos5ecc and delete the others.
@miquelduranfrigola ?

**Comment by miquelduranfrigola** [comment]
Thanks @GemmaTuron 

A few disorganized thoughts:

- I would abandon eos5ecc iupac2smiles since there is not iupac input for now.
- fs-mol-protonet was a lot of work from @Amna-28 and we were very close to finishing it. She did a great job. The compound embedding from @leoank is very similar, so I think we can archive this model for now.
- gem-representation-learning was extremely difficult. I would archive it.
- pmapper-3d-pharmacophore is very interesting, looking into natural products. I would work on it.
- molpmolfit was essentially done, so let's revise it and finish it.
- agree we should finish redial-2020
- I am unsure about embeddings-extractions an cardpred

I agree with you, we can open the discussion and prioritize. Thanks for this, @GemmaTuron

**Comment by GemmaTuron** [comment]
We are:
- Finishing redial.200 (@simrantan)
- Re-trained eos30gr (@febielin )
- We will eliminate eos3d3r and eos54ij, since their servers are not reliable and there is no source data available
- We have archived eos1bba
- If we can we will work with @emmakodes for the text input for model eos5ecc
- Maybe @febielin can try to work on eos5y9f if it was close to being complete, once she is done with current tasks

**Comment by GemmaTuron** [comment]
Update:
- We have incorporated eos8fth (redial-2020) and retrained eos30gr
- We have paused the input text adapter for the time being
- We are working on eos5y9f
- We have archived eos1bba, eos54ij and eos3d3r
