### ISSUE TITLE
🦠 Model Request: DMPNN-hERG

### ISSUE THREAD

**Issue by russelljeffrey** [ersilia-os/ersilia#750]
### Model Name

Prediction of hERG Channel Blockers with Directed Message Passing Neural Networks

### Model Description

The model uses invertible flow-based model for generating unique molecules with desired properties. The model ultimately generates molecular graphs. In this model, the directed message passing neural network (D-MPNN) is applied to construct classification models for identifying hERG blockers based on diverse datasets.

### Slug

hERG-Channel-Blockers-Prediction

### Tag

hERG, channel-blockers, DMPNN

### Publication

https://pubs.rsc.org/en/content/articlehtml/2022/ra/d1ra07956e

### Source Code

https://github.com/AI-amateur/DMPNN-hERG

### License

MIT

**Comment by leilayesufu** [comment]
@GemmaTuron after writing the approve command, i was waiting for the GitHub actions bot reply, but I found in actions that "Command 'approve' is not configured for the user's permission level 'read'."

**Comment by GemmaTuron** [comment]
Hi @leilayesufu !
Indeed, only admin level contributors can approve models. You can start by trying out the original code, and once we are sure the code is working we can approve the model and go onto incorporating it in Ersilia. I'll approve the model request but I strongly suggest first trying the original code to make sure it works. More details in Ersilia's documentation :)

**Comment by leilayesufu** [comment]
@GemmaTuron I've ran the original code and it works.
I tried incorporating it into the model hub and one of the checks is failing at the predict output
```
Error message:

Ersilia exception class:
EmptyOutputError

Detailed error:
Model API eos30f3:run did not produce an output

Hints:
- Visit the fetch troubleshooting site

If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /home/runner/eos/current.log
Error: Process completed with exit code 1.
```


This is the pull request https://github.com/ersilia-os/eos30f3/pull/4

**Comment by GemmaTuron** [comment]
Hi @leilayesufu !

Thanks, a few questions:
- Did you face any issues in running the original code? Can you detail which steps you took to that end?
- Did you try to first run the model directly running the `bash run.sh` command?
- Next, have you tried fetching locally from `--repo path`?

**Comment by GemmaTuron** [comment]
Also, the commands in the DockerFile cannot create another conda environment inside the conda environment that will be created, you just need to add the installs as `RUN pip install` or `RUN conda-forge`
The python version is specified at the top

```
# Create Conda environment
RUN conda create -n chemprop python=3.8

# Activate Conda environment
SHELL ["conda", "run", "--no-capture-output", "-n", "chemprop", "/bin/bash", "-c", "source activate chemprop"]

# Install RDKit and other dependencies
#RUN conda install -c conda-forge rdkit

RUN pip install rdkit
```

And I don't see any changes in the actual code, only in the metadata and the dockerfile

**Comment by GemmaTuron** [comment]
Hi @leilayesufu 

Seems from the message there is a file that is needed and is not found? Have you looked what is this file and where is it called? Always try to understand the error you are getting.
Also, always first before opening a PR, test the model, first by creating a conda environment with the required packages and runnning the run.sh file and then by trying to fetch the model with the Ersilia CLI locally. All these steps are well detailed in the Model Contribution sections of the documentation, make sure to follow them.

**Comment by leilayesufu** [comment]
HI @GemmaTuron 

Models available for so many different datasets, which is of interest to us

<img width="711" alt="table2" src="https://github.com/ersilia-os/ersilia/assets/78659709/3b60b54c-b353-45da-85ea-313330302711">

They have provided model checkpoints for something called the moe206 descriptors and something else called noFP (does this mean no finger print?) - how does one work with moe206 descriptor?
They have also provided separate checkpoints for each of the folds in 5 fold cross val, should we just use the checkpoints from the last fold?

**Comment by leilayesufu** [comment]
Thank you for help @GemmaTuron .
Here is my PR: https://github.com/ersilia-os/eos30f3/pull/5

**Comment by GemmaTuron** [comment]
Hi @leilayesufu!

Thanks, good start. I see you have added the Checkpoints for the No Fingerprints Model in the Checkpoints folder, and the Chemprop code in Framework. This is all good.

What you should revise now is `main.py`. I don't fully understand what you are trying to do from line 35 onwards. Here we want to load the model checkpoints and make predictions for any input file we use, but I am unsure what .csv files you are trying to read. Can you clarify that part?

**Comment by leilayesufu** [comment]
HI @GemmaTuron , Good morning and happy new week.
**Explanation of my commit and PR.**
This is the model we're trying to incorporate. https://github.com/AI-amateur/DMPNN-hERG/tree/main/example_notebook


This is the file i'm incorporating in the main.py file. https://github.com/AI-amateur/DMPNN-hERG/blob/main/Table1_entry1/Script_for_Reproduce_result_entry1.sh

So from line 35 in my main.py file is line 45 in the script it loops over the five folds in the checkpoints folder and save the predictions of the input file through the five folds into predict_absolute_path{0-4}

Then i got the value across eachof the 5 folds results and calculated the mean and saved the mean prediction into the output.csv file.
Then i deleted the generated predict_absolute_path{0-4} files.

side note: The original script generates five output predictions looping through fold 0- fold4, so i got all the output predictions and calculated their mean and saved it into the output.csv file.

**Comment by GemmaTuron** [comment]
Hi @leilayesufu !

Thanks, the link is helpful to understand where you took the code from. this piece of code is used to get the exact results to reproduce the publication figures. This is good for reproducing the original model, but what we want now is to implement the model for new molecules.
This means, we don't want to read the `preds_test.csv `files created but new `.csv` files. There is a function in chemprop called `make_predictions` that should iterate over the different folds and give the result directly.

The original main.py structure should help you: you "only" need to modify the `my_model` function so that it loads the right chemprop model and returns the `make_predictions` result on any set of molecules passes. I've also pointed above another eos model using chemprop that might be helpful to understand what I mean

**Comment by leilayesufu** [comment]
Hi @gemma, Thank you very much for your help.
I've updated the main.py file accordingly to use chemprop and 
here is my PR: https://github.com/ersilia-os/eos30f3/pull/5

**Comment by GemmaTuron** [comment]
Hi @leilayesufu 

It looks better now, thanks. Before merging the PR please:
- Clean up all prints from the files you have modified
- Improve the description of the model to be more accurate, instead of copying the publication abstract, which does not reflect the model we are implementing here. Since it is the first one, I am providing here an example: _This model leverages the ChemProp network (D-MPNN, see original Stokes et al, Cell, 2020 for more information) to build a predictor of hERG-mediated cardiotoxicity. The model has been trained using a dataset published by Cai et al, J Chem Inf Model, 2019, which contains 7889 molecules with several cut-offs for hERG blocking activity. The authors select a 10 uM cut-off. This implementation of the model does not use any specific featurizer, though the authors suggest the moe206 descriptors (closed-source) improve performance even further._
- The License is None, as there is no license specified by the authors in their repo
- The Interpretation should be clearer: _Probability of blocking hERG (cut-off: 10uM)_
- Eliminate unwanted files (i.e: mock.csv)

**Comment by leilayesufu** [comment]
Okayyy, thank you!
I’ll work on that now

**Comment by leilayesufu** [comment]
Updated, thank you!

**Comment by GemmaTuron** [comment]
This model is incorporated!
