### ISSUE TITLE
🦠 Model Request: SmallWorld Sampler

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#764]
### Model Name

SmallWorld Sampler

### Model Description

SmallWorld is an index of chemical space containing more than 230B molecular substructures. SmallWorldSampler uses the Small World API to post a query to the SmallWorld server to sample smiles.

### Slug

small-world-sampler

### Tag

Similarity, ZINC

### Publication

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3606195/

### Source Code

https://pypi.org/project/smallworld-api/

### License

MIT

**Comment by GemmaTuron** [comment]
@samuelmaina when you finish with your tasks, would you continue with this model incorporation?

**Comment by miquelduranfrigola** [comment]
I did major updates to this model, as it was not doing the right thing - it was treating the input as an ensemble.
It now works.

However, I have marked it as "In progress" in AirTable. The reason is that this model is too slow in my opinion, because it samples from too many "maps" in Small World. I would rather have individual small world samplers in different models.

Therefore, I have created `small-world-enamine-real`, `small-world-wuxi` and `small-world-zinc` instead of `small-world`. This is much faster and more robust.

@GemmaTuron  In case you like this approach, please feel free to delete the *eos7emx* model from our repository & close this issue.

**Comment by GemmaTuron** [comment]
I've archived the repository https://github.com/ersilia-os/eos7emx/ and eliminated the model from our records
