### ISSUE TITLE
[🐕 Batch]: Sanitize AirTable in a cron job

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#768]
We have started to work on the following class to sanitize AirTable periodically: 

https://github.com/ersilia-os/ersilia/blob/master/ersilia/db/hubdata/sanitize.py

This needs to be populated with checks. A related cron job will be:

https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/sanitize-hub.yml

**Comment by miquelduranfrigola** [comment]
Hello @carcablop - I think you discussed with @GemmaTuron about this?

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola and @carcablop 

What we discussed is that the first step will be to create a simple GitHub Action that will periodically convert the Airtable backend into a .csv file - easier to check and manipulate. That is not an urgent task, so we will tackle it when possible

**Comment by GemmaTuron** [comment]
Update: @carcablop is working on that feature, thanks! 🎉

**Comment by miquelduranfrigola** [comment]
Hi! May I ask about the current status of this?

**Comment by miquelduranfrigola** [comment]
Quick **update**. I have created an "scan models" in the `ersilia-stats` repository that may be (partially) related to this issue. In brief, this action looks for models that have a repository in the `ersilia-os` organization profile but, nonetheless, they are **not** registered in AirTable. For each of these models, an issue is opened with a "maintenance" label. For now, I've put this action in the `ersilia-stats` repository, but feel free to move it to the `ersilia` repo if you think it makes more sense.

**Comment by miquelduranfrigola** [comment]
Hi @carcablop and @GemmaTuron ! Did we make any progress on this front? Let me know if there is anything I can do to help.

**Comment by miquelduranfrigola** [comment]
> Hi @miquelduranfrigola and @carcablop
> 
> What we discussed is that the first step will be to create a simple GitHub Action that will periodically convert the Airtable backend into a .csv file - easier to check and manipulate. That is not an urgent task, so we will tackle it when possible

Specifically, I would start with this very simple suggestion by @GemmaTuron

**Comment by carcablop** [comment]
Hello @miquelduranfrigola.
Apologies for not having responded sooner.
I have made a little progress on this, I created the YAML file for the workflow and a script that operates converting the backend to a csv file, although I have not tested it. Please allow me to update my changes tomorrow, and we can review that. I will manage it in the ersilia repository.
Do you want the csv file to be saved in a specific location?
Thank you so much.

**Comment by miquelduranfrigola** [comment]
Thanks @carcablop 

I would save the CSV file in this location: https://github.com/ersilia-os/ersilia/tree/master/ersilia/hub/content , perhaps in a subfolder called `data`? So: `ersilia/hub/content/data/models.csv`, for example?

**Comment by carcablop** [comment]
Thanks @miquelduranfrigola 
Some changes I made:
[yml file ](https://github.com/carcablop/ersilia/blob/master/.github/workflows/airtable_to_csv.yml)
[script](https://github.com/carcablop/ersilia/blob/master/.github/scripts/convert_airtable_to_csv.py)
I'm not sure if the airtable base ID is correct.

**Comment by miquelduranfrigola** [comment]
Hello @carcablop , I have been looking into the current `models.tsv` file being generated and the format is not ideal. It seems AirTable cannot be naturally exported to a tabular format, mostly because of the presence of inner lists.

On a second thought, I feel it would be much better to store it in JSON format, which is way more flexible. So, having a `models.json` instead of a `models.tsv`. What do you all think, @DhanshreeA @GemmaTuron @carcablop ?

**Comment by miquelduranfrigola** [comment]
Hello @DhanshreeA @carcablop and @GemmaTuron 

I wonder if, in addition to the cron job, we could use a webhook to trigger the event: https://airtable.com/developers/web/guides/webhooks-api

This would be ideal since it would allow us to get rid of the AirTable interface with the Ersilia CLI (and the read-only key now exposed in: https://github.com/ersilia-os/ersilia/blob/master/config/read_only_keys.json). In practice, users would only interact with the `models.json` file.

**Comment by carcablop** [comment]
I made the changes, if you agree to save it in a JSON file, [this will work](https://github.com/ersilia-os/ersilia/commit/e9cbe6eb70944f65817bcad0521022e62202e75f).

**Comment by GemmaTuron** [comment]
Hello @carcablop @miquelduranfrigola 

Many models are missing their related airtable entry - since this is the only recent work we have been doing on airtable I suspect there is a problem with the pipeline - I cannot explain it otherwise. I've noted for example eos9taz, and eos4qda missing. Or is the change in the read only key that has allowed some unwanted access @miquelduranfrigola ? This is critical

**Comment by miquelduranfrigola** [comment]
I have found a solution to this through personal access tokens, @GemmaTuron - I hope it works now.

**Comment by miquelduranfrigola** [comment]
> Hello @carcablop @miquelduranfrigola
> 
> Many models are missing their related airtable entry - since this is the only recent work we have been doing on airtable I suspect there is a problem with the pipeline - I cannot explain it otherwise. I've noted for example eos9taz, and eos4qda missing. Or is the change in the read only key that has allowed some unwanted access @miquelduranfrigola ? This is critical

Hey @GemmaTuron thanks. I am at a loss here. In which file they are missing? In the `.tsv` or the `.json` file?

**Comment by GemmaTuron** [comment]
they were not on airtable, promise, in any view or without any filter.

**Comment by miquelduranfrigola** [comment]
OK they are there now.

**Comment by DhanshreeA** [comment]
> Quick **update**. I have created an "scan models" in the `ersilia-stats` repository that may be (partially) related to this issue. In brief, this action looks for models that have a repository in the `ersilia-os` organization profile but, nonetheless, they are **not** registered in AirTable. For each of these models, an issue is opened with a "maintenance" label. For now, I've put this action in the `ersilia-stats` repository, but feel free to move it to the `ersilia` repo if you think it makes more sense.

Oh I believe some of these model repositories also correspond to dud repositories created as a result of unsuccessful approve command dispatch.

**Comment by miquelduranfrigola** [comment]
Hi all, since we are doing this within a GitHub Actions, I am thinking that we should be storing the `models.json` file in AWS S3 instead of GitHub. We have the credentials to write to S3 already as a GitHub secret, so this should not be a big issue. The file would be publicly accessible and equally easy to maintain in S3, I think.

@DhanshreeA do you agree? Any strong reason not to do so?

**Comment by miquelduranfrigola** [comment]
As for the "interface" to the `json` file, we could simply have it here: https://github.com/ersilia-os/ersilia/blob/master/ersilia/db/hubdata/interfaces.py

At the moment, we have an `AirtableInterface` class.

We could write something similar:

```python
JsonModelsInterface(...):
    def __init__(...):
        ...

    def _read_json_file(...):
        ...

    def items(...):
         yield ...

    def all_items(...):
        return
```

We could then use this class as a drop-in replacement for `AirtableInterface`

**Comment by miquelduranfrigola** [comment]
Hi @carcablop,

To keep us all on the same page, could you please summarize the next steps based on Friday's meeting?

Thankyou!

**Comment by carcablop** [comment]
Hi @miquelduranfrigola @DhanshreeA and @GemmaTuron .
In summary, to contextualize, starting from what is currently incorporated in ersilia, we have an action that allows us to download Airtable data every night and save it in a tsv file. This task was changed due to the complexity of managing the data in tsv, therefore the following was proposed:

- [ ] 1. Create the cron that downloads the data from airtable and saves it in a JSON file. That file will then be uploaded to AWS S3.

In the last meeting, we discussed some of the problems that we would have when trying to eliminate the dependency of Airtable with Ersilia, and that is that starting from the fact that we have a cron that is updated every night and additionally, data is also uploaded to Airtable, for example when We load a model, we are going to present a synchronization problem in the information since in the automation of the workflow that model will not be found due to the lack of immediate update or synchronization at the same time of update and upload to Airtable and S3. In short, we would be having an information synchronization problem. That is why the following is proposed:

1. Using webhooks to detect Airtable changes.
2. Possibility of modifying some scripts where the metadata is updated to Airtable. Possibly consider modifying this script  ["update_metadata_to_airtable.py"](https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/test-model.yml#L56) that it inserts metadata at the same time as uploading the information to S3.

For now, the solution of modifying scripts is easier compared to using webhooks.

For now, we will continue working on the following:

- [ ] Create a cron that downloads from Airtable models and saves them to a JSON file and uploads them to s3.
- [ ] Create a class that allows you to interact with S3 to get the JSON file and interact only with the models.json file.

**Comment by miquelduranfrigola** [comment]
Thanks @carcablop , this is very useful.
Agree that webhooks is too complicated. Let's not do it.

**Comment by DhanshreeA** [comment]
Sounds good @carcablop , let me know if I can assist in any way.

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA @carcablop @miquelduranfrigola 

Should we take this up again? The tsv file is still there and gets updated every day making the git pulls and pushes unnecessarily long

**Comment by carcablop** [comment]
> Hi @DhanshreeA @carcablop @miquelduranfrigola
> 
> Should we take this up again? The tsv file is still there and gets updated every day making the git pulls and pushes unnecessarily long

Hello @GemmaTuron 
Apologize for the git pulls and pushes unnecessarily for a long time. With the last PR [https://github.com/ersilia-os/ersilia/pull/1102](https://github.com/ersilia-os/ersilia/pull/1102), the models will not be saved in a .tsv file, the models should be uploaded to S3 as a .json file without the need to push changes to the repository. 
@DhanshreeA @miquelduranfrigola I would like to validate if the data of the models was saved in S3 or if the one that already exists was updated since I cannot validate it because I do not have access.  In the last action run yesterday [https://github.com/ersilia-os/ersilia/actions/runs/8698881741/job/23856552720](https://github.com/ersilia-os/ersilia/actions/runs/8698881741/job/23856552720) it did not throw any issues and file 'models.json' was uploaded. Thanks you

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

I believe this has been completed. For the purpose of traceability, can you summarise how is the airtable data being saved, cleaned and downloaded currently before closing the issue? Thanks

**Comment by DhanshreeA** [comment]
A nightly [cron job](https://github.com/ersilia-os/ersilia/blob/master/.github/workflows/airtable_to_json.yml) is run which takes a data dump from Airtable and uploads this as a models.json in our S3. This models.json is publicly readable making it accessible within Ersilia without the need for credentials.
