### ISSUE TITLE
Install Ersilia with Poetry

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#772]
We should install Ersilia using Poetry instead of the `setup.py` file.

It should be relatively easy to do by inspecting the current `setup.py`. Please ignore the `check_bentoml` call for now.

**Comment by y1450** [comment]
Hi @miquelduranfrigola can I help with it. I have used poetry to manage projects.
Recently setup docaarray on local machine using poetry. For a reference: https://github.com/docarray/docarray/blob/main/pyproject.toml

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 

When we refactor the installs, we should move the Fuzzywuzzy install to the test version of ersilia only. IF I do that now, the workflows will fail because it still looks for this package even if it is only related to the test command.
I've added it to the slim version for the moment

**Comment by GemmaTuron** [comment]
btw, just to take it into account, I get the following message:
```
/home/gturon/anaconda3/envs/ersilia/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```
after installing fuzywuzzy

**Comment by miquelduranfrigola** [comment]
Thanks @GemmaTuron - a quick fix would be a conditional import of the ModelTester class only if the installation was done in test mode.

**Comment by miquelduranfrigola** [comment]
> Hi @miquelduranfrigola can I help with it. I have used poetry to manage projects. Recently setup docaarray on local machine using poetry. For a reference: https://github.com/docarray/docarray/blob/main/pyproject.toml

Thanks @y1450 ! Greatly appreciated! I am meeting with @DhanshreeA today who was initially assigned with the task. I thik we are well covered, but in any case we'll get back to you with any updates. Thanks for your help and interest.

**Comment by miquelduranfrigola** [comment]
Hello @DhanshreeA and @y1450 

@DhanshreeA was able to provide a `pyproject.toml` and, as far as I can tell, all tests have passed successfully: e3c5d79e15ae0cf21b848aff90ce747e90521d1d

I will close this issue for now. We can reopen it if we encounter any problems, especially in dockerization and with the model templates.

Amazing work, @DhanshreeA - thanks so much!

**Comment by GemmaTuron** [comment]
Hi,

The upload to s3 is failing with this new Ersilia, which is missing the boto3 package:
https://github.com/ersilia-os/eos8fma/actions/runs/6082196802/job/16499446871

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron, thanks for flagging this. I just looked into it. So a few things are happening here and I'll explain them here:

- Ersilia depends on boto3 directly for publishing to s3, however, it was not specified as a direct dependency in the previous [setup.py.](https://github.com/ersilia-os/ersilia/blob/master/setup.py) . However, boto3 is a [dependency for bentoml](https://github.com/ersilia-os/bentoml-ersilia/blob/34a26149d92b5dc4a09b6f51aaaa85b3d8116ae4/setup.py#L60) and it was getting installed because of that. 
- The installation with poetry installs bentomly lazily, it doesn't install bentoml until no command requiring bentoml is run. I think this is by design with poetry/pyproject.toml. 
- Since none of the jobs in [this workflow](https://github.com/ersilia-os/eos8fma/actions/runs/6082196802/workflow) involve running a command requiring bentoml, it never gets installed, therefore boto3 does not get installed.

**Proposed solution**
I propose we simply add boto3 as a direct dependency within ersilia itself. What do you both think? @miquelduranfrigola

**Comment by GemmaTuron** [comment]
Thansk @DhanshreeA, very clear!
Seems installing boto3 upfront would be the best?

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron, done! I accidentally pushed directly to master :sweat_smile: but all the workflows are passing. And I verified that boto3 gets installed even if bentoml is not run. Can you re run the s3 workflow within the model?

**Comment by GemmaTuron** [comment]
yes that works!

**Comment by GemmaTuron** [comment]
yes! thanks for the super fast response @DhanshreeA :)
