### ISSUE TITLE
How Ersilla Model Hub will help in future for mankind. It is not mentioned anywhere.

### ISSUE THREAD

**Issue by AnshuKumari197** [ersilia-os/ersilia#80]
**What is your feature request?**
A clear concise descritprion of what you want to happen.

**Is your feature request related to a problem?**

**Describe alternatives you've considered**

**Additional context**

**Comment by victorabba** [comment]
I'm interested in this issue.

**Comment by AnshuKumari197** [comment]
@GemmaTuron Can i make documentation file on this??

**Comment by Shamswaggirl** [comment]
@GemmaTuron shall I contribute for this issue?

**Comment by Shamswaggirl** [comment]
- As it is open source to all, it's the key point which addresses whoever is interested to contribute or researching drugs can access this hub without any regrets. Ersilia provisions a remote laboratory for researchers, for instance, we all are familiar with Covid-19, which caused lots of deaths however we are safe now due to the invention of vaccination. 

- If everybody gets access to research and tries working with drugs, whatever novel disease comes the solution can be made very instantly. This is the vital role of the Ersilia model hub.

- Since Ersilia is enabled with AI/ML technology, it can cope with future-driven technologies and modern mankind. If it is enabled in all OS, it will be great to use in the future.

**Comment by Ye7ni** [comment]
@AnshuKumari197 
Hello
I'd very much like to be assigned this task as I believe my input would be needed. Thank you

**Comment by Rufaida98** [comment]
Interesting approach. Good idea

**Comment by GemmaTuron** [comment]
Hello all,

We have added some more structure on the contribution tasks for Outreachy applicants. Please check the Slack channel and follow the instructions, you can take this idea there @AnshuKumari197 
I am closing this issue to move the discussion to the appropriate thread
