### ISSUE TITLE
Make ersilia conda-installable

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#9]
# Background
Currently, Ersilia can be pip-installed. We have a GitHub Action to update ersilia on PyPi every time we do a new release. However, pip installation does not ensure that extra requirements (such as git-lfs) are installed. Perhaps having ersilia as a conda package would be desirable as well.

# Requested feature
Make ersilia conda-installable and trigger a GitHub Action every to update the ersilia conda repository on every new release of the package.

**Comment by IdealisticINTJ** [comment]
Hi @miquelduranfrigola,
I'd like to work on this issue. Please assign it to me.

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola  I tried to make this package conda installable but it keeps breaking down on conda build command. That's because there are dependencies which are not present on Conda. The problem is that conda package dependencies only refer to other conda packages. I also tried to repackage the dependencies not present on conda and then publish them in my channel but again, the conda build failed because they have dependencies which are not present on conda. For now, I have opened issues in dependencies which aren't on conda to make them conda package. Meanwhile, I'm also looking for work around this issue.
![image](https://user-images.githubusercontent.com/54634163/160336853-7eddbd05-3c28-491d-9c0a-92b10d632b35.png)

![image](https://user-images.githubusercontent.com/54634163/160336906-a5276baa-031a-415b-b8b6-7576d49ab4b9.png)

**Comment by GemmaTuron** [comment]
hello @IdealisticINTJ and @anamika-yadav99 

Thanks for your interest to contribute to this. TPlease, first refer to issue #36 before continuing the work here.
@anamika-yadav99, please also go to issue #36 before and we will then work on this issue

**Comment by miquelduranfrigola** [comment]
Hi @anamika-yadav99 thanks for your contribution here. These dependencies should be pip-installable, if I am not mistaken. If you install pip in the conda environment, is it possible to then install these packages with the pip command?

**Comment by anamika-yadav99** [comment]
@miquelduranfrigola  Yes the dependencies are pip-installable but they aren't conda-installable.  Dependencies are required to be conda installable to build a conda package.

**Comment by miquelduranfrigola** [comment]
Hi @anamika-yadav99 thanks a lot. The conda skeleton solution that you suggest seems to be a good option: https://stackoverflow.com/questions/64916092/how-do-i-install-pip-packages-through-a-conda-build-recipe

**Comment by anamika-yadav99** [comment]
Hi @miquelduranfrigola  I'm on it.

**Comment by miquelduranfrigola** [comment]
Hi @anamika-yadav99 I am closing the issue now. All is well noted and some folk volunteers who are writing Github Actions with us will use your contribution. So I greatly appreciate it.

Will reopen in case any problems emerge!
