### ISSUE TITLE
Create custom issue template v1

### ISSUE THREAD

**Issue by seanmarcia** [ersilia-os/ersilia#906]
We need a custom issue template for researchers to submit their molecules to.

For v1 of the template it should denote that it will be running against model `eos3b5e`

There should be a textarea for them to input their molecules in.

**Comment by miquelduranfrigola** [comment]
Thanks @seanmarcia 

As you write this custom issue template, if you can, let's try to make it as generalistic as possible. So, instead of saying input "molecules", for instance, we can say input "data".

The reason is that, as we grow the Ersilia Model Hub, more and more models will appear that do not have small molecules as input (the current case), but they can extend to proteins or even cells. This will come in the future, but it is probably good to plan ahead.

Please let me know if this makes sense.

**Comment by DhanshreeA** [comment]
@GemmaTuron @miquelduranfrigola good to close this issue?

**Comment by GemmaTuron** [comment]
yes!
