### ISSUE TITLE
Ersilia to provide validation script for molecules

### ISSUE THREAD

**Issue by seanmarcia** [ersilia-os/ersilia#908]
It was mentioned that there is a script that is run to validate that data entered is correct/valid. Ersilia needs to provide that so we can implement it as an action.

**Comment by GemmaTuron** [comment]
Hi @seanmarcia is this the same as #911 ?

**Comment by miquelduranfrigola** [comment]
Hi @seanmarcia 

This is already done by Ersilia to a large extend when we run a model. If the file is not correct, it will crash? Do you think this is enough, or should we have a validation script previous to running?

If so, I would just do a simple validaton:
- File extension is CSV
- File contains only one column (the SMILES)

**Comment by miquelduranfrigola** [comment]
Alternatively, I can create some simple functionality such as `ersilia test --input input.csv` but I think that it would be overkill, since the action will have to install ersilia. As mentioned above, if we just write a couple of lines inside the workflow file to check extension and check that there is one and only one column, that should be sufficient for now.

**Comment by DhanshreeA** [comment]
@miquelduranfrigola or @GemmaTuron good to close this issue?

**Comment by GemmaTuron** [comment]
yes!
