### ISSUE TITLE
Issue forms

### ISSUE THREAD

**Issue by Sukriti-sood** [ersilia-os/ersilia#91]
Creating Issue Templates using the Issue forms and replacing the markdown files with YAML files.

The issue form looks like this:---

![New-Issue-·-moja-global-community-website](https://user-images.githubusercontent.com/55010599/161384401-57bc4903-57c7-47d4-a468-5bcb82c4456b.png)

Also, the Outreachy Documentation template is not generated correctly, I also want to update that using yaml.

**Comment by Sukriti-sood** [comment]
@GemmaTuron Please assign me this issue, if you find it good enhancement.

**Comment by GemmaTuron** [comment]
Hello @Sukriti-sood,

Thanks for the suggestions:
- Outreachy templates: this was still work in progress, now it is well placed as an .md file, please do not modify it. 
- Having yaml forms instead of .md files: I like your idea for some of the issues, could you confirm before proceeding that we can have both  issue forms (.yaml) and regular issue templates (.md) in the same repo? We are not ready to upgrade all issues to Markdown.

And check the Slack channel, where we will now post how to continue contributing to the project

**Comment by Sukriti-sood** [comment]
> Hello @Sukriti-sood,
> 
> Thanks for the suggestions:
> 
> * Outreachy templates: this was still work in progress, now it is well placed as an .md file, please do not modify it.
> * Having yaml forms instead of .md files: I like your idea for some of the issues, could you confirm before proceeding that we can have both  issue forms (.yaml) and regular issue templates (.md) in the same repo? We are not ready to upgrade all issues to Markdown.
> 
> And check the Slack channel, where we will now post how to continue contributing to the project

yes @GemmaTuron we can have both (yaml) and (.md) firmatts for issue templates.

**Comment by GemmaTuron** [comment]
Thanks @Sukriti-sood 

Then, can I ask you to:
1) Create GitHub issue using the appropriate template (see issues opened by other applicants already) and work through the initial tasks?
2) Link this issue in a comment under your github issue and start working on it

This way we have all contributions from each applicant in a single thread easier to follow!
thanks!

**Comment by Sukriti-sood** [comment]
> Thanks @Sukriti-sood
> 
> Then, can I ask you to:
> 
> 1. Create GitHub issue using the appropriate template (see issues opened by other applicants already) and work through the initial tasks? Are you interested in the Documentation or Code project?
> 2. Link this issue in a comment under your github issue and start working on it
> 
> This way we have all contributions from each applicant in a single thread easier to follow! thanks!

Thanks @GemmaTuron , I will create issue.

**Comment by harshita214** [comment]
@GemmaTuron Can I also work on this issue with @Sukriti-sood if it's alright 

I would be happy to help and create an issue form for **documentation issues** since as of now there are these 3 categories of issue forms apart from outreachy forms. So if its alright can I work on this part @GemmaTuron 


![image](https://user-images.githubusercontent.com/79797000/164865996-bb8929df-5c99-4d0e-9ff7-fc334415c01b.png)

**Comment by harshita214** [comment]
@GemmaTuron 

> @GemmaTuron Can I also work on this issue with @Sukriti-sood if it's alright
> 
> I would be happy to help and create an issue form for **documentation issues** since as of now there are these 3 categories of issue forms apart from outreachy forms. So if its alright can I work on this part @GemmaTuron
> 
> ![image](https://user-images.githubusercontent.com/79797000/164865996-bb8929df-5c99-4d0e-9ff7-fc334415c01b.png)

**Comment by miquelduranfrigola** [comment]
@GemmaTuron - can we revise this issue and close it if solved?

**Comment by GemmaTuron** [comment]
Hi all,

We now have all the issue templates we need in a nice format, so I am closing this issue!
