### ISSUE TITLE
🦠 Model Request: HDAC3i-Finder

### ISSUE THREAD

**Issue by Richiio** [ersilia-os/ersilia#916]
### Model Name

Identifying HDAC3 inhibitors

### Model Description

A model trained with XGBoost as the algorithm and Morgan2 fingerprints for features. It predicts HDAC3 inhibitors present in a given compound returning Active and Not Active depending on the activity. 

### Slug

Anticancer-agents

### Tag

Cancer, ChemBL

### Publication

https://onlinelibrary.wiley.com/doi/10.1002/minf.202000105

### Source Code

https://github.com/jwxia2014/HDAC3i-Finder

### License

GPL-3.0

**Comment by Richiio** [comment]
@GemmaTuron New issue created for suggested model for incorporation

**Comment by Richiio** [comment]
Hi @GemmaTuron @HellenNamulinda. This model has been successfully tested and is working. Here is a pull request to that
https://github.com/ersilia-os/eos1n4b/pulls

**Comment by Richiio** [comment]
Here is the output csv


[output.csv](https://github.com/ersilia-os/ersilia/files/13679552/output.csv)

**Comment by HellenNamulinda** [comment]
Hello @Richiio,
Great work :clap: 

However, I have a suggestion for the output.
Running the model using the run.sh returns three columns, 
```
SMILES,Bioactivity_pre,Probability_active
c1(nc2c([nH]1)ccc(c2)OC(F)F)S(=O)Cc1c(c(ccn1)OC)OC,Active,0.9937094449996948
```
And that might return a list(three values with column 1 and column2 being nulls) instead of a single value when run within ersilia.

Ersilia output for this model is a single float; **Probability_active**. 
How about we return that probability? and not all the three three columns?

Since that output for run.sh is good as it helps one to know the input smiles and their scores, we shouldn't drop the columns at that point.

But a slight change in service.py
 ```
    R += [
                    {"outcome": [Float(x) for x in r]}
                ]  # <-- EDIT: Modify according to type of output (Float, String...)
```
to 
```
                R += [
                    {"outcome": [Float(x) for x in r[1]}
                ]  # <-- EDIT: Modify according to type of output (Float, String...)
```
will return only the last column(**Prob_active**) whenever the model is run within ersilia.

**Comment by Richiio** [comment]
Thanks @HellenNamulinda. Null error has been fixed @GemmaTuron

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda and @Richiio 

Thanks for the work. I completely agree with @HellenNamulinda that is best to return only the result as the probability, but, in order to keep it more consistent with other Ersilia models, I suggest to avoid modifying the `service.py` unless it is really essential - simply in the `main.py` select the probability column and return this as output, @Richiio . Hope this makes sense as well. Just to clarify, Hellen's option is good but we are really trying to homogenize models and keep the service and pack files as they are. Let me know once the changes are incorporated!

**Comment by Richiio** [comment]
Output before edit


[output2.csv](https://github.com/ersilia-os/ersilia/files/13712617/output2.csv)

Output after edit


[output.csv](https://github.com/ersilia-os/ersilia/files/13712619/output.csv)

**Comment by Richiio** [comment]
For the first implementation, we were having a list of [SMILES, bioactivity, prediction_active] but the second was modified to just return the prediction_active @HellenNamulinda @GemmaTuron

**Comment by HellenNamulinda** [comment]
Perfect @Richiio :clap: ,
I've seen the changes made in the [PR](https://github.com/ersilia-os/eos1n4b/pull/3)

**Comment by GemmaTuron** [comment]
@Richiio I've left comments on the PR and on Slack, please check and update the code, thanks!

**Comment by GemmaTuron** [comment]
Hi @Richiio 

Any updates on this model?

**Comment by GemmaTuron** [comment]
This model is incorporated, thanks @Richiio !
